server:
  port: 5000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${user.dir}\\src\\main\\resources\\configsa
management:
  endpoints:
    web:
      exposure:
        include: "*"